# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomographyGUI.ui'
#
# Created: Mon Nov 30 20:39:09 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 581)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadSource = QtGui.QPushButton(self.centralwidget)
        self.loadSource.setGeometry(QtCore.QRect(10, 10, 92, 27))
        self.loadSource.setObjectName("loadSource")
        self.loadTarget = QtGui.QPushButton(self.centralwidget)
        self.loadTarget.setGeometry(QtCore.QRect(400, 10, 92, 27))
        self.loadTarget.setObjectName("loadTarget")
        self.viewSource = QtGui.QGraphicsView(self.centralwidget)
        self.viewSource.setEnabled(True)
        self.viewSource.setGeometry(QtCore.QRect(10, 50, 391, 281))
        self.viewSource.setObjectName("viewSource")
        self.acquirePts = QtGui.QPushButton(self.centralwidget)
        self.acquirePts.setGeometry(QtCore.QRect(411, 350, 101, 27))
        self.acquirePts.setCheckable(True)
        self.acquirePts.setObjectName("acquirePts")
        self.point1 = QtGui.QLineEdit(self.centralwidget)
        self.point1.setGeometry(QtCore.QRect(530, 350, 113, 27))
        self.point1.setObjectName("point1")
        self.point2 = QtGui.QLineEdit(self.centralwidget)
        self.point2.setGeometry(QtCore.QRect(650, 350, 113, 27))
        self.point2.setObjectName("point2")
        self.point4 = QtGui.QLineEdit(self.centralwidget)
        self.point4.setGeometry(QtCore.QRect(650, 390, 113, 27))
        self.point4.setObjectName("point4")
        self.point3 = QtGui.QLineEdit(self.centralwidget)
        self.point3.setGeometry(QtCore.QRect(530, 390, 113, 27))
        self.point3.setObjectName("point3")
        self.elabel = QtGui.QLabel(self.centralwidget)
        self.elabel.setGeometry(QtCore.QRect(440, 450, 62, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.elabel.setFont(font)
        self.elabel.setAlignment(QtCore.Qt.AlignCenter)
        self.elabel.setObjectName("elabel")
        self.effectBox = QtGui.QComboBox(self.centralwidget)
        self.effectBox.setGeometry(QtCore.QRect(530, 440, 231, 27))
        self.effectBox.setObjectName("effectBox")
        self.effectBox.addItem("")
        self.effectBox.addItem("")
        self.effectBox.addItem("")
        self.effectBox.addItem("")
        self.effectBox.addItem("")
        self.effectBox.addItem("")
        self.effectBox.addItem("")
        self.transform = QtGui.QPushButton(self.centralwidget)
        self.transform.setGeometry(QtCore.QRect(450, 500, 92, 27))
        self.transform.setObjectName("transform")
        self.reset = QtGui.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(560, 500, 92, 27))
        self.reset.setObjectName("reset")
        self.save = QtGui.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(670, 500, 92, 27))
        self.save.setObjectName("save")
        self.viewTarget = QtGui.QGraphicsView(self.centralwidget)
        self.viewTarget.setEnabled(True)
        self.viewTarget.setGeometry(QtCore.QRect(410, 50, 391, 281))
        self.viewTarget.setObjectName("viewTarget")
        self.acquireSpts = QtGui.QPushButton(self.centralwidget)
        self.acquireSpts.setGeometry(QtCore.QRect(10, 340, 101, 27))
        self.acquireSpts.setCheckable(True)
        self.acquireSpts.setObjectName("acquireSpts")
        self.spoint1 = QtGui.QLineEdit(self.centralwidget)
        self.spoint1.setGeometry(QtCore.QRect(120, 340, 113, 27))
        self.spoint1.setObjectName("spoint1")
        self.spoint2 = QtGui.QLineEdit(self.centralwidget)
        self.spoint2.setGeometry(QtCore.QRect(120, 380, 113, 27))
        self.spoint2.setObjectName("spoint2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSource.setText(QtGui.QApplication.translate("MainWindow", "Load Source", None, QtGui.QApplication.UnicodeUTF8))
        self.loadTarget.setText(QtGui.QApplication.translate("MainWindow", "Load Target", None, QtGui.QApplication.UnicodeUTF8))
        self.acquirePts.setText(QtGui.QApplication.translate("MainWindow", "Acquire Points", None, QtGui.QApplication.UnicodeUTF8))
        self.elabel.setText(QtGui.QApplication.translate("MainWindow", "Effect", None, QtGui.QApplication.UnicodeUTF8))
        self.effectBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Nothing", None, QtGui.QApplication.UnicodeUTF8))
        self.effectBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Rotate 90°", None, QtGui.QApplication.UnicodeUTF8))
        self.effectBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Rotate 180°", None, QtGui.QApplication.UnicodeUTF8))
        self.effectBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Rotate 270°", None, QtGui.QApplication.UnicodeUTF8))
        self.effectBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Flip Horizontally", None, QtGui.QApplication.UnicodeUTF8))
        self.effectBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Flip Vertically", None, QtGui.QApplication.UnicodeUTF8))
        self.effectBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Transpose", None, QtGui.QApplication.UnicodeUTF8))
        self.transform.setText(QtGui.QApplication.translate("MainWindow", "Transform", None, QtGui.QApplication.UnicodeUTF8))
        self.reset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("MainWindow", "Save...", None, QtGui.QApplication.UnicodeUTF8))
        self.acquireSpts.setText(QtGui.QApplication.translate("MainWindow", "Acquire Points", None, QtGui.QApplication.UnicodeUTF8))

