#! /bin/bash
#
#$Author: ee364e07 $
#$Date: 2015-08-25 16:44:48 -0400 (Tue, 25 Aug 2015) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/F15/students/ee364e07/Lab00/Script2 $
#$Revision: 80154 $

count=$@

for ((i=$count;i>=0;i--))
do
    echo  ${i}

done

exit 0
