#! /bin/bash
#
#$Author: ee364e07 $
#$Date: 2015-08-25 16:48:49 -0400 (Tue, 25 Aug 2015) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/F15/students/ee364e07/Lab00/Script3 $
#$Revision: 80162 $

count=$@

for ((i=$count;i>=0;i--))
do
    if (($i % 3 == 0))
    then
        echo ${i}
    fi

done

exit 0
